### ISSUE TITLE
add support for multi-line squee notifications

### ISSUE THREAD

**Issue by jamesmanning** [Trellmor/BerryTube#11]
When I get a squee, there's a nice notification that comes from the app, and if I catch it fast enough, I can switch back to the chat app and see the original message in the scrollback.  However, the original message is usually longer than can fit in one notification line and is truncated (with ellipsis).  If it's been too long since the message came in (so it's not available in the current scrollback buffer), then AFAICT there's no way to tell what the original message was (outside of the first few words that fit on the one line).

Here's me from the BT main interface sending a too-long message to me on the chat app (while the chat app isn't active), and the resulting truncated notification.

![screenshot_2014-12-03-08-07-42](https://cloud.githubusercontent.com/assets/225626/5280835/860b8d2a-7ac4-11e4-925f-eb449d14346d.png)

**Comment by jamesmanning** [comment]
wow - it was a lot more code than I had expected - for some reason I thought it'd be just passing something like a multi-line option to what you were already doing and telling it to wrap instead of truncate with ellipsis.  Sorry about that.

But thanks so much for doing it!  That rocks! :+1:

**Comment by Trellmor** [comment]
Yeah, but this way it has some nice bonuses, like the scrollback buffer can be way bigger, since the chat messaged are cached in a database instead of in the memory. And notifications will persist between sessions.

**Comment by jamesmanning** [comment]
Absolutely - it's so awesome! :thumbsup:
