### ISSUE TITLE
RFE: option to allow links to always open in incognito window

### ISSUE THREAD

**Issue by jamesmanning** [Trellmor/BerryTube#13]
currently there's no easy way (AFAICT) to have a link open in an incognito window instead of a normal one.  while having a long-touch context menu open on the link is one option, I'm not sure if that's easily doable or not, and might conflict with the long-touch mechanism.  In many cases (like amazon links), it's nice to have it open incognito just to keep it from affecting the 'recently viewed items' set as well.

**Comment by Trellmor** [comment]
Links are handled by the TextView, and not in the app. Also, it's not possible to specify that a link should be opened in an incognito/private browsing window. Sorry, but it's currently not possible to do.
