### ISSUE TITLE
Can't login with new version of app (1.5.1)

### ISSUE THREAD

**Issue by jamesmanning** [Trellmor/BerryTube#20]
can't login with the new version of the app from either my Nexus 5 nor Nexus 9 trying different accounts.

Is there any kind of logging I can/should enable that might help identify the cause?

**Comment by Trellmor** [comment]
Uuh, I think I know what went wrong. Will post a news version asap

**Comment by jamesmanning** [comment]
okey dokey - in case it helps any, my credentials before clicking LOGIN are the same as usual:

![image](https://cloud.githubusercontent.com/assets/225626/8805382/f24d6c1c-2f9e-11e5-8457-84a4a15e697f.png)

Then after clicking LOGIN, it goes to the normal chat window, shows some of the scrollback from the last time I was able to login, but it stays as 'Anonymous'.  

![image](https://cloud.githubusercontent.com/assets/225626/8805425/2fce1eec-2f9f-11e5-9123-309685faf32d.png)

As a completely random guess, it's no longer handling the socket.io responses correctly? Dunno

**Comment by Trellmor** [comment]
Uh, no. There is leftover debug code that I forgot to remove. I failed to test the final release on the actual website.

Unfortunately my internet connection is currently down, so it will take me a few more hours to release an update.

You can also get the new version from https://github.com/Trellmor/BerryTube/releases/tag/1.5.2

Sorry for the inconvenience.
